---
files:
  # A glob based folder lookup
  - loc: "~/folder1"
    threshold:
      glob: "*.log"
      times: 5
      period: 30s
      patterns:
        - ".*FATAL.*"
        - ".*payment failed.*"
      notify: "email"
  # An explicit log file
  - loc: "~/folder2/explicit.log"
    threshold:
      times: 1
      period: 1m
    patterns:
      - ".*disk space low.*"
    notify: "slack"

## TBD
integrations:
    slack:
      webhook: ""
    email:
      to:
        - "alerts@bar.com"
        - "admin@bar.com"
