---
files:
  # A glob based folder lookup
  - glob: "~/logs/*.txt"
    threshold:
      hits: 5
      period: 30s
      patterns:
        - ".*FATAL.*"
        - ".*payment failed.*"
      notify: "email"
  # An explicit log file
  - glob: "~/logs/foo.log"
    threshold:
      hits: 1
      period: 1m
    patterns:
      - ".*disk space low.*"
    notify: "slack"

## TBD
integrations:
    slack:
        webhook: ""
    email:
        to:
            - "alerts@bar.com"
            - "admin@bar.com"